### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by Lunaphied** [krille-chan/fluffychat#1000]
- Operating system: ios
- Version: 1.19.0

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.60a25d75-7f7b-4d22-a71c-0364bf052e9a)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by zgypa** [comment]
This happens for me only when i receive an audio message from Element. Or actually it doesn't happen when another user sends me an audio message using fluffychat.

**Comment by krille-chan** [comment]
Closing as duplicate of #928 (audio: MissingPluginException iOS)
