### ISSUE TITLE
Error after rotating screen vertically

### ISSUE THREAD

**Issue by zgypa** [krille-chan/fluffychat#1002]
### Bug Description

```
Bad state: RenderBox was not laid out: RenderFractionalTranslation#8f5f0
#0      RenderBox.size (package:flutter/src/rendering/box.dart:1994)
#1      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2952)
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3352)
#3      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2619)
#4      _FloaterState.build.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/src/common/base/floater.dart:359)
#5      Builder.build (package:flutter/src/widgets/basic.dart:7698)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#17     _OverlayPortalElement.update (package:flutter/src/widgets/overlay.dart:2063)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#32     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#46     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#51     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#57     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#58     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#72     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#78     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#80     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#81     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#87     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#88     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#97     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#109    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#131    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#133    Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#134    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#138    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#144    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#146    Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#147    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#150    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#156    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#160    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#170    Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#171    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#185    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#189    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#192    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#200    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#202    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#205    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#207    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#210    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#212    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#215    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#216    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#220    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#223    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#224    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#227    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#228    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#229    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#232    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#233    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#236    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#238    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#241    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#243    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#251    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#253    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#256    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#257    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#260    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#261    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#262    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#264    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#266    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#268    Element.updateChildren (package:flutter/src/widgets/framework.dart:3973)
#269    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#272    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#273    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#274    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#275    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#276    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#277    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#278    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#279    _invoke (dart:ui/hooks.dart:312)
#280    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
#281    _drawFrame (dart:ui/hooks.dart:283)
```

### Steps to Reproduce

1. Rotate phone horizontally
2. rotate phone vertically

### Expected Behavior

The expected behavior is that no error appears, and the screen rotates back vertically.

### App Version

1.19.0

### Additional Platform Information

iPhone 13 mini

**Comment by krille-chan** [comment]
Duplication of https://github.com/krille-chan/fluffychat/issues/974
