### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by astronema21** [krille-chan/fluffychat#1023]
- Operating system: ios
- Version: 1.19.0

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.9800c651-0eeb-469a-8d1d-d996641ed47b)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by krille-chan** [comment]
Closing as duplicate of #928
