### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by salixh5** [krille-chan/fluffychat#1097]
iOS 17.4.1
FluffyChat 1.20.0

MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.d0051b61-27c9-48f0-9165-c3f88a033831)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:982)
<asynchronous suspension>

**Comment by Artiom-M** [comment]
The same for me. Audio messages created in Fluffy chat are ok, but those sent from my Elements on Android triggers the error

**Comment by maste9** [comment]
Same on MacOS Sonoma 14.1 with ogg-files that are sent by a script with commandline messenger. Work with fluffy on Android as on Sonoma in SchildiChat(Elements flavored).

**Comment by krille-chan** [comment]
Closing as duplicate of #928
