### ISSUE TITLE
[BUG]: Error Widget when changing from the vertical view to the horizontal in iOS

### ISSUE THREAD

**Issue by sci-42ver** [krille-chan/fluffychat#1165]
The log is
```
Bad state: RenderBox was not laid out: RenderFractionalTranslation#02683
#0      RenderBox.size (package:flutter/src/rendering/box.dart:2201)
#1      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2936)
#2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3354)
#3      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2886)
#4      _FloaterState.build.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/src/common/base/floater.dart:359)
#5      [Builder.build](https://web.telegram.org/a/Builder.build) (package:flutter/src/widgets/basic.dart:7695)
#6      [StatelessElement.build](https://web.telegram.org/a/StatelessElement.build) (package:flutter/src/widgets/framework.dart:5557)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#17     _OverlayPortalElement.update (package:flutter/src/widgets/overlay.dart:2069)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#32     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#46     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#49     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#51     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#57     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#58     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#72     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#78     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#80     Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
#81     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#85     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#87     Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
#88     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#97     StatefulElementupdate (package:flutter/src/widgets/framework.dart:5673)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#105    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#109    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#119    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#121    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#127    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#131    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#133    Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
#134    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#138    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#144    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#146    ElementupdateChildren (package:flutter/src/widgets/framework.dart:3976)
#147    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#150    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#151    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#152    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#153    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#154    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#156    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#160    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#164    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#167    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#168    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#169    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#170    Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
#171    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#175    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#183    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#185    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#189    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#192    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#200    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#202    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#205    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#207    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#208    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#210    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#212    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#213    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#214    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#215    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#216    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#217    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#219    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#220    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#223    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#224    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#227    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#228    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#229    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#232    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#233    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#234    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#235    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#236    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#238    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#241    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#243    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/frameworkdart:5512)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#251    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#253    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#256    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#257    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563)
#258    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#259    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#261    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#263    Element.updateChildren (package:flutter/src/widgets/framework.dart:3976)
#264    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6929)
#265    Element.updateChild (package:flutter/src/widgets/framework.dart:3827)
#266    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512)
#267    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#269    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905)
#270    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136)
#271    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443)
#272    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392)
#273    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313)
#274    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171)
#275    _invoke (dart:ui/hooks.dart:312)
#276    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#277    _drawFrame (dart:ui/hooks.dart:283)
```

**Comment by jakehamilton** [comment]
Same issue I am hitting in #1109. Only realized today it was due to orientation change.

**Comment by jakehamilton** [comment]
Just updated the app to 1.23.0 and it looks like rotating from portrait to landscape works<sup>1</sup>, but rotating back from landscape to portrait results in a black screen. The app no longer crashes, but must be restarted when the bug occurs since it is in an unusable state.

Screenshots of landscape working and then what happens when you rotate back to portrait:

![IMG_0603](https://github.com/user-attachments/assets/4101523c-f150-4601-9dc5-fd5279e8e5c5)
![IMG_0604](https://github.com/user-attachments/assets/b075288b-84c3-42ae-a564-5d14a25d7952)

---

1. You may have noticed from the screenshot that the app isn't taking safe area into account when in landscape mode. This *should* be a small fix, but I am not familiar with how Flutter apps handle this so please forgive me if it is more complex 😅

**Comment by sci-42ver** [comment]
@jakehamilton FYI, recently while doing one automatic update of iOS app, I found this problem is solved by fluffychat developers at least in v1.26.1.
