### ISSUE TITLE
Voice Messages Fail

### ISSUE THREAD

**Issue by nordrune** [krille-chan/fluffychat#1167]
### Bug Description

After verifying successfully on fluffy with my dendrite matrix homeserver account. Old voice messages fail to played/loaded: 

Log:

MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.49567072-5b79-4d21-b3be-47c176bca4b7)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:982)
<asynchronous suspension>

### Steps to Reproduce

1. log in and verify 
2. attempt to play an old voice message

### Expected Behavior

old decrypted voice message should be playable

### App Version

1.12.0

### Additional Platform Information

iPhone 14 pro

**Comment by krille-chan** [comment]
Closing as duplicate of #928 (audio: MissingPluginException iOS)
