### ISSUE TITLE
[BUG]: Unable to connect to server


### ISSUE THREAD

**Issue by rodolforg** [krille-chan/fluffychat#1197]
But it is working when using other clients in the same device.

It continuously shows "no server connection" message in loop.

Then I tried to watch a video clip O received, just to check, and got this error message:

ClientException with SocketException: Connection failed (OS Error: Network is unreachable, errno = 101), address = [redacted], uri = [redacted]
#0      IOClient.send (package:http/src/io_client.dart:154)
<asynchronous suspension>
#1      TimeoutHttpClient.send (package:matrix/src/utils/http_timeout.dart:47)
<asynchronous suspension>
#2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#3      Event.downloadAndDecryptAttachment.<anonymous closure> (package:matrix/src/event.dart:614)
<asynchronous suspension>
#4      Event.downloadAndDecryptAttachment (package:matrix/src/event.dart:615)
<asynchronous suspension>
#5      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:42)
<asynchronous suspension>

**Comment by opk12** [comment]
Any chance your firewall may have an intermittent bug? I have connection failure in Fluffy when I turn on [RethinkDNS](https://github.com/celzero/rethink-app), whose GitHub issue 1550 causes the domain matrix-client.matrix.org to sometimes resolve to an IPv6 address, while I'm in an IPv4 network. To work around it, I close and reopen the app 2-3 times, until it resolves to IPv4.

**Comment by rodolforg** [comment]
It was a IPv6 only issue... :/
