### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by DauerndamProgrammieren** [krille-chan/fluffychat#1214]
error:
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.f7e9e466-0e00-454d-a6cc-f7c91babcb0b)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:982)
<asynchronous suspension>

**Comment by krille-chan** [comment]
Closing as duplicate of #928
