### ISSUE TITLE
[BUG]: Unable to play video

### ISSUE THREAD

**Issue by iaxat** [krille-chan/fluffychat#1233]
This event hasn't any attachment or thumbnail.
#0      Event.downloadAndDecryptAttachment (package:matrix/src/event.dart:589)
#1      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:42)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)
#10     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425)
#11     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)
#12     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)
#13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)
#14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)
#15     _invoke1 (dart:ui/hooks.dart:328)
#16     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#17     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

**Comment by krille-chan** [comment]
Closing as duplicate of #941
