### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by everypizza1** [krille-chan/fluffychat#1237]
To reproduce:
1. open up a chat on desktop
2. press someone's profile picture to view details
3. switch chat in sidebar
4. observe error

Log: 
```
Provider<MatrixState> not found for SliverList
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343)
#1      Provider.of (package:provider/src/provider.dart:293)
#2      Matrix.of (package:fluffychat/widgets/matrix.dart:61)
#3      UserBottomSheetView.build (package:fluffychat/pages/user_bottom_sheet/user_bottom_sheet_view.dart:30)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#7      StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#12     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#16     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#20     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#37     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#44     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#53     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#60     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#64     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#67     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#69     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#89     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#92     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#93     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#99     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#111    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#114    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#115    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#116    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#117    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#122    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#124    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#126    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#127    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#129    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#130    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#131    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#135    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#136    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#141    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#147    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#151    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#159    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#160    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#164    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#170    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#174    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#177    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#179    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#182    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#184    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3824)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505)
#187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5196)
#189    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904)
#190    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989)
#191    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448)
#192    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
#193    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311)
#194    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169)
#195    _invoke (dart:ui/hooks.dart:312)
#196    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399)
#197    _drawFrame (dart:ui/hooks.dart:283)
```

**Comment by everypizza1** [comment]
Solved in latest `main`.
