### ISSUE TITLE
[BUG]: Unable to play video

### ISSUE THREAD

**Issue by Written0489** [krille-chan/fluffychat#1246]
Hi. I clicked play on a video sent by DM on my Samsung s24 running android 14 and fluffychat 1.21.2

```Unable to decrypt file
#0      Event.downloadAndDecryptAttachment (package:matrix/src/event.dart:643)
<asynchronous suspension>
#1      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:42)
<asynchronous suspension>
```

**Comment by krille-chan** [comment]
Closing as duplicate of #1038
