### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by Avid-Xenoblade-Player** [krille-chan/fluffychat#1249]
Don't know what happened.
"Provider<minified:Ia> not found for minified:a2C

    at Object.j (https://fluffychat.im/web/main.dart.js:5805:19)
    at Object.W (https://fluffychat.im/web/main.dart.js:5814:14)
    at Object.am (https://fluffychat.im/web/main.dart.js:54445:20)
    at aCl.A (https://fluffychat.im/web/main.dart.js:105546:21)
    at RD.kn (https://fluffychat.im/web/main.dart.js:149256:32)
    at RD.Ap (https://fluffychat.im/web/main.dart.js:149234:9)
    at RD.abD (https://fluffychat.im/web/main.dart.js:149186:10)
    at RD.eZ (https://fluffychat.im/web/main.dart.js:149258:6)
    at ma.r0 (https://fluffychat.im/web/main.dart.js:149012:3)
    at ma.Ap (https://fluffychat.im/web/main.dart.js:149238:31)"
![Screenshot 2024-07-28 19 25 52](https://github.com/user-attachments/assets/8ab7b159-36f8-466d-8aee-f5a104dd1939)
Hardware: ChromeOS 126.0.6478.132
Browser: Chrome Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36,gzip(gfe)

**Comment by Avid-Xenoblade-Player** [comment]
actually, this has been documented in an already-open issue, #1237 . closing.
