### ISSUE TITLE
[BUG]: Unable to play video

### ISSUE THREAD

**Issue by theotheroracle** [krille-chan/fluffychat#1351]
```
Unable to decrypt file
#0      Event.downloadAndDecryptAttachment (package:matrix/src/event.dart:752)
<asynchronous suspension>
#1      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:42)
<asynchronous suspension>
```

**Comment by krille-chan** [comment]
Closing as duplicate of #1038
