### ISSUE TITLE
fluffychat struggles with SVG files

### ISSUE THREAD

**Issue by anarcat** [krille-chan/fluffychat#1353]
### Bug Description

I can't seem to select an SVG icon for a room in Fluffychat. I can pick a PNG, but the file picker (at least in Linux desktop), doesn't consider "image files" to include SVG.

### Steps to Reproduce

1. go to a room
2. in the three dots menu, pick "room details"
3. click on the camera
4. "open gallery"
5. see only PNG images, no SVG

also:

1. click on the "+" sign next to the chat line
2. choose "send file"
3. pick a SVG file
4. click send ("send original" doesn't matter)
5. see the following backtrace:

```
Null check operator used on a null value
#0      MatrixImageFile.resizeImplementation (package:matrix/src/utils/matrix_file.dart:258)
#1      NativeImplementationsDummy.shrinkImage (package:matrix/src/utils/native_implementations.dart:117)
#2      compute.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:19)
#3      _RemoteRunner._run (dart:isolate:1090)
#4      _RemoteRunner._remoteExecute (dart:isolate:1084)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

and finally:

1. upload a SVG from Element into a room
2. go into Fluffychat
3. look at room, SVG looks like this:

![image](https://github.com/user-attachments/assets/96ed9592-9e96-4618-b7a6-69cd502e3f43)

Note that fluffychat doesn't seem to render SVG icons in rooms avatars either, but i'm less sure of that.

### Expected Behavior

I should be able to upload SVG files to rooms. Failing this, I shouldn't get a backtrace, and I should be able to just upload the file without fluffychat trying (and failing) to do a conversion).

For what it's worth, Element is fine uploading, viewing, and setting as avatar, SVG files.

### App Version

1.22.1

### Additional Platform Information

Debian bookworm, installed through flatpak

### Additional Context

This is similar to #299 which was closed for inactivity, but is still relevant.

**Comment by UnicodeMan** [comment]
Issue is still here. I noticed Element web/ Element app handles svg files file.
When user sends me a svg, i can see the preview in message.
With fluffychat it doesn't work.

**Comment by u9000-Nine** [comment]
Same. On version 2.5.1, except I don't even see the preview:

<img width="549" height="404" alt="Image block showing a generic image icon instead of the actual image" src="https://github.com/user-attachments/assets/470acbe2-7b21-4529-95dc-b621d7b75f08" />

**Comment by Pietagorh** [comment]
## Additional steps to reproduce
SVG's in emoji packs won't display either

<details><summary>Screenshots (i don't want to flood)</summary>
<img width="684" height="870" alt="Image" src="https://github.com/user-attachments/assets/77186bfc-e4f4-443c-a33f-b7f0bca4de04" />

<img width="1080" height="2198" alt="Image" src="https://github.com/user-attachments/assets/69037812-f8b6-48e8-a8ea-e28b7d9f578e" />
</details>

## Stack trace
```
# [DEBUG] Unable to render mxc image - Exception: Invalid image data
#0      _futurize (dart:ui/painting.dart:8570)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:8351)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2575)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147)
#4      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:1719)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1021)
<asynchronous suspension>
```
