### ISSUE TITLE
[BUG]: Unable to send file

### ISSUE THREAD

**Issue by thorstenfx** [krille-chan/fluffychat#1400]
cannot add attachments or pictures in fluffychat web. with element web (same account it works). 

M_NOT_FOUND: Not found

    at Object.j (https://fluffychat.im/web/main.dart.js:5789:19)
    at fR.d_ (https://fluffychat.im/web/main.dart.js:234907:21)
    at https://fluffychat.im/web/main.dart.js:236107:16
    at chj.a (https://fluffychat.im/web/main.dart.js:7206:63)
    at chj.$2 (https://fluffychat.im/web/main.dart.js:75797:14)
    at cfc.$1 (https://fluffychat.im/web/main.dart.js:75791:21)
    at aO1.HD (https://fluffychat.im/web/main.dart.js:77274:33)
    at c2z.$0 (https://fluffychat.im/web/main.dart.js:76281:11)
    at Object.Tg (https://fluffychat.im/web/main.dart.js:7363:40)
    at al.II (https://fluffychat.im/web/main.dart.js:76206:3)

**Comment by hailey** [comment]
I also get this error when I try and send files with fluffychat web or android. This happens on multiple accounts on my server,

> M_UNRECOGNIZED: Unrecognized request
> j@https://fluffychat.im/web/main.dart.js:5789:19
> d_@https://fluffychat.im/web/main.dart.js:234907:21
> QD/$async$QD<@https://fluffychat.im/web/main.dart.js:236107:16
> l/s@https://fluffychat.im/web/main.dart.js:7206:64
> $2@https://fluffychat.im/web/main.dart.js:75797:14
> $1@https://fluffychat.im/web/main.dart.js:75791:21
> HD@https://fluffychat.im/web/main.dart.js:77274:33
> $0@https://fluffychat.im/web/main.dart.js:76281:11
> Tg@https://fluffychat.im/web/main.dart.js:7363:40
> II@https://fluffychat.im/web/main.dart.js:76206:3
> $0@https://fluffychat.im/web/main.dart.js:76251:13
> daE@https://fluffychat.im/web/main.dart.js:7395:5
> dbA@https://fluffychat.im/web/main.dart.js:7397:7
> $1@https://fluffychat.im/web/main.dart.js:75737:3

This seemed to have happened suddenly  around the time this bug report was opened and other clients such as schildichat, element, nheko, all are able to send files and pictures.
