### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by nolith** [krille-chan/fluffychat#1475]
Attempting to play a voice message resulted in this error.

```
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.107e9c9b-930a-48b2-a596-f6f30d1ff188)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:990)
<asynchronous suspension>

```

**Comment by krille-chan** [comment]
Closing as duplicate of #928
