### ISSUE TITLE
[BUG]: Unable to load timeline

### ISSUE THREAD

**Issue by RossComputerGuy** [krille-chan/fluffychat#1527]
```
ClientException: Software caused connection abort, uri=https://matrix-client.matrix.org/_matrix/client/v3/rooms/!FMiswSlMesncBVFXfI%3Amatrix.org/messages?from=s5493423396_757284974_48559545_3301619147_3614819488_262995096_1423230623_11057339063_0_400038&dir=b&limit=100&filter=%7B%22lazy_load_members%22%3Atrue%7D
#0      IOClient.send (package:http/src/io_client.dart:156)
<asynchronous suspension>
#1      TimeoutHttpClient.send (package:matrix/src/utils/http_timeout.dart:49)
<asynchronous suspension>
#2      Api.getRoomEvents (package:matrix/matrix_api_lite/generated/api.dart:4465)
<asynchronous suspension>
#3      Room.requestHistory (package:matrix/src/room.dart:1280)
<asynchronous suspension>
#4      Timeline._requestEvents (package:matrix/src/timeline.dart:169)
<asynchronous suspension>
#5      Timeline.requestHistory (package:matrix/src/timeline.dart:95)
<asynchronous suspension>
#6      ChatController._tryLoadTimeline (package:fluffychat/pages/chat/chat.dart:270)
<asynchronous suspension>
```

**Comment by krille-chan** [comment]
Closing as duplicate of #1401
