### ISSUE TITLE
The Matrix HQ room went wrong to load old messages.

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#176]
#### Description
The #matrix:matrix.org went wrong to load old messages.

#### To Reproduce
Enters in the room and scrolls the app to see old messages, in the logs appers this error above, i think is related to action

```
# [ERROR] Capture exception - RangeError (start): Invalid value: Not in inclusive range 0..18: 19
#0      RangeError.checkValidRange (dart:core/errors.dart:333)
#1      ListMixin.getRange (dart:collection/list.dart:393)
#2      FamedlySdkHiveDatabase.getEventList (package:matrix/src/database/hive_database.dart:395)
<asynchronous suspension>
#3      Timeline.requestHistory (package:matrix/src/timeline.dart:82)
<asynchronous suspension>
#4      ChatController.requestHistory (package:fluffychat/pages/chat.dart:108)
<asynchronous suspension>
```

Btw... has the warning in the logs too:

```
# [WARNING] Something went wrong:  - RangeError (start): Invalid value: Not in inclusive range 0..18: 19
```

#### Additional information:
- Device: Samsung Galaxy A31
- OS and OS version: Android 11
- Installed version of FluffyChat: v0.42.0
- (Android only) Which store are you using: Play Store
- (Android only) Are Google Services available: Yes

**Comment by krille-chan** [comment]
Should be fixed already
