### ISSUE TITLE
"Empty Chat" as title of some rooms

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#407]
#### Description

Room titles are being shown as "Empty chat" for *some* group chats on iOS.
Its fine on fluffychat web & element.

#### To Reproduce

I have this happening on the following rooms:

https://matrix.to/#/#docs:ansible.com    

https://matrix.to/#/#community:ansible.com    

https://matrix.to/#/!kDYMmhJUsdeGgGGYwz:matrix.org?via=matrix.org&via=jupiterbroadcasting.com&via=linuxdelta.com    

I simply joined them and the title never became the actual title of the room and is instead simply shown as "Empy chat".
Everything else works fine with these rooms. (messages etc.)

#### Additional information:
- Device: iPhone 12
- OS and OS version: iOS 15.6 
- Installed version of FluffyChat: 1.5.0 
~~- (Android only) Which store are you using: ~~
~~- (Android only) Are Google Services available: ~~

The only issue that sounded similar at first glance was #46, but the issue is completely differently. 

Only message in the log:

```
[ERROR] Capture exception - Null check operator used on a null value

#0 ChatDetailsView.build.. (package:fluffychat/pages/chat_details/chat_details_view.dart:226)
#1 SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:471)
#2 SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1236)
#3 SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1169)
#4 Iterable.forEach (dart:core/iterable.dart:325)
#5 SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1213)
#6 SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1146)
#7 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#8 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#9 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#10 ProxyElement.update (package:flutter/src/widgets/framework.dart:5154)
#11 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#12 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#13 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#14 RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825)
#15 MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375)
#16 _ViewportElement.update (package:flutter/src/widgets/viewport.dart:237)
#17 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#18 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#19 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#20 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#21 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#22 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#23 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#24 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#25 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#27 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977)
#28 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#29 StatefulElement.update (package:flutter/src/widgets/framework.dart:5009)
#30 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#31 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#32 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#33 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#34 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#35 ProxyElement.update (package:flutter/src/widgets/framework.dart:5154)
#36 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#37 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#38 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#39 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#40 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#41 ProxyElement.update (package:flutter/src/widgets/framework.dart:5154)
#42 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#43 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#44 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977)
#45 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#46 StatefulElement.update (package:flutter/src/widgets/framework.dart:5009)
#47 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#48 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#49 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#50 ProxyElement.update (package:flutter/src/widgets/framework.dart:5154)
#51 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#52 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832)
#53 Element.rebuild (package:flutter/src/widgets/framework.dart:4529)
#54 StatelessElement.update (package:flutter/src/widgets/framework.dart:4883)
#55 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#56 SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6222)
#57 Element.updateChild (package:flutter/src/widgets/framework.dart:3530)
#58 _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135)
#59 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597)
#60 _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153)
#61 RenderObject.invokeLayoutCallback. (package:flutter/src/rendering/object.dart:2025)
#62 BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2516)
#63 RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025)
#64 RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227)
#65 _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316)
#66 RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757)
#67 PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
#68 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504)
#69 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892)
#70 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370)
#71 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#72 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083)
#73 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997)
#74 _rootRun (dart:async/zone.dart:1426)
#75 _CustomZone.run (dart:async/zone.dart:1328)
#76 _CustomZone.runGuarded (dart:async/zone.dart:1236)
#77 _invoke (dart:ui/hooks.dart:151)
#78 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#79 _drawFrame (dart:ui/hooks.dart:115)
```

**Comment by M00NJ** [comment]
I'd like to add, that you cannot leave or delete the empty chat. It just displays a "no permission" message (see recording). Also this is not exclusive to IOS. I'm on Android 13.

https://github.com/krille-chan/fluffychat/assets/82398591/48d16638-49fd-4cf0-bfc4-8d637d4c00d0

**Comment by Mikaela** [comment]
Have you tried sending `/clearcache` in any room to clear your local FluffyChat cache and reload it from the server?

**Comment by M00NJ** [comment]
Yes, I did that half a year ago and it fixed it. It said something about a Telegram Bridge error after that, if I remember correctly. I haven't had this happen again since then and forgot about my comment on this issue.
