### ISSUE TITLE
Notifications doesn't work properly on Android with UnifiedPush

### ISSUE THREAD

**Issue by parrazam** [krille-chan/fluffychat#544]
### Bug Description

I have 2 accounts registered in FluffyChat, one using the default server `matrix.org` and another one using a custom server. I'm using Ntfy as notification server.

When I add both accounts in the app, the first one register the device in the Ntfy server. However, the second one doesn't. So I can receive notifications for the first account but not for the second one.

### Steps to Reproduce

1. Log in in the app with an account.
2. Check that the notification device is registered under Settings -> Notifications -> Devices
3. Log in with another account from a different server.
4. Go to Settings -> Notifications -> Devices and no one device was registered.
5. Send a message to the first account. It will be notified.
6. Send a message to the second account. It won't be notified :(

### Expected Behavior

Each account should register in the unifiedpush server, in order to manage notifications independently.

### App Version

1.13.0

### Additional Platform Information

Device: OnePlus 8T, OS: Android 13

**Comment by marcan** [comment]
This is stilll broken.

**Comment by Doomsdayrs** [comment]
Just found this out as I was starting to use FluffyChat for my multiple accounts

**Comment by cassandracomar** [comment]
I tested this by enabling and disabling notifications for each account. each time I do so for one account, I can receive notifications for that account (DMs only -- notifications for group chats never work) but not the other.

**Comment by TimSchimansky** [comment]
Yes this is also happening with the google play version, which I installed in the hope to fix this, but I only get DM-notifications for the first account. (Both are custom servers)

**Comment by squatica** [comment]
If you are really desperate, here is how to register a pusher manually by directly calling the matrix API:

First you will need you access token and the url of the matrix api.

Api url is easy, take the domain part of your account name (such as "matrix.org") and look at https://matrix.org/.well-known/matrix/client - if they show `m.homeserver` -> `base_url` then that is the API url, if not, then the domain part of your account name is the API url. Matrix.org has api at `https://matrix-client.matrix.org`. Do this for both of your accounts and let's call them `MATRIX_HOST_1` and `MATRIX_HOST_2`.

To get the access tokens, you can either steal them from a web client by inspecting the Authorization headers (any access token of the particular user account should work). I don't know how to get it from Fluffychat, but we could just do a new login on command line:

***(Be extra careful with that access token, and that curl command containing your password. If you don't know how to avoid leaking them, or accidentally storing them in some cache or history, don't proceed.)***

```
curl -XPOST -H "Content-Type: application/json" \
  -d '{"type":"m.login.password","identifier":{"type":"m.id.user","user":"YourUsernameHere"},"password":"YourPasswordHere"}' \
  "${MATRIX_HOST_1}/_matrix/client/v3/login"
```

Get both access tokens, let's call them `ACCESS_TOKEN_1` and `ACCESS_TOKEN_2`.

Get the pusher settings from the first account (the one where push notifications work):

```
curl -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${ACCESS_TOKEN_1}" \
  "${MATRIX_HOST_1}/_matrix/client/v3/pushers"
```

From the response take only the object inside `pushers:[...]` and add this part: `"append":true` - this can be done with `jq`:

```
curl ..../pushers | jq -rc '.pushers[0]+{append:true}'
```

Now send the resulting json object to the second account's api, to set the pusher:

```
curl -XPOST -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${ACCESS_TOKEN_2}" \
  --data '{"app_display_name":"..."... ,"append":true}' \
  "${MATRIX_HOST_2}/_matrix/client/v3/pushers/set"
```

This will effectively clone the exact same UnifiedPush settings from your first account. Now fluffy should be getting the notifications, however it's not 100% ideal, seems like fluffy will show the username of the first account, but at least the notification is there and clicking it opens the correct room in correct account.

Of course this is super hacky solution, so only do this if you are willing to solve whatever breaks. So far it seems to have worked for me, YMMV.

**Comment by Yarrax** [comment]
It's still actual bug.
Android 14, Fluffy 1.22.0
I receive push from first account and dont receive form second account.

**Comment by gusarg81** [comment]
> It's still actual bug. Android 14, Fluffy 1.22.0 I receive push from first account and dont receive form second account.

Yes, the same is happening to me too currently.

**Comment by baltevl** [comment]
I have written pr #1443 to fix this. Any feedback and/or testing is welcome :)

**Comment by DearFox** [comment]
I get notifications for the first account I signed out of.

When I try to open the notification I get an error:

```
Push Helper has crashed! - Exception: Unable to find event for this push notification! 
#0 Client.getEventByPushNotification (package:matrix/src/client.dart:1863) 
#1 _tryPushHelper (package:fluffychat/utils/push_helper.dart:94) 
#2 pushHelper (package:fluffychat/utils/push_helper.dart:31) 
#3 BackgroundPush._onUpMessage (package:fluffychat/utils/background_push.dart:424)
```

Any ideas on how I can fix this are welcome

**Comment by konekohana** [comment]
Can confirm that @squatica's hack works for me <3 It doesn't display any details about the message, but I do get notification about new messages for the second profile too now, which is better than no notifications at all.

**Comment by Curve** [comment]
I'm also unable to receive notifications. I have only one account registered in the app, which is using a custom matrix server.  
Would be extremely appreciated if this could get fixed properly :)

**Comment by djmaze** [comment]
I had a similar problem after signing out and signing in with another account.

In order to fix this, I swiped out the FluffyChat app and (in the ntfy app) removed the ntfy topic belonging to Fluffy. After a restart of Fluffy, it now seems to work.

**Comment by tobiasBora** [comment]
Still confirm the bug is here 2 years later. I picked FluffyChat precisely because of the multiple account support, and so far it was a great experience… but without notification this is fairly useless, what a pity. Any official plan to support it in the foreseable futur @krille-chan? (sorry for the dirty ping, but seems like this is important enough to have an official answer)

Also, just realized it was already discussed in https://github.com/krille-chan/fluffychat/issues/169 and I also have no notifications from the desktop app.

**Comment by Curve** [comment]
> Still confirm the bug is here 2 years later. I picked FluffyChat precisely because of the multiple account support, and so far it was a great experience… but without notification this is fairly useless, what a pity. Any official plan to support it in the foreseable futur @krille-chan? (sorry for the dirty ping, but seems like this is important enough to have an official answer)
> 
> Also, just realized it was already discussed in https://github.com/krille-chan/fluffychat/issues/169 and I also have no notifications from the desktop app.

I am only signed in into one account on the app and get no notifications - I'm not sure if this is the exact same issue as described here as I'm not even using multi-accounts

**Comment by wrenix** [comment]
Could we change the titleof this issue to:
```patch
-Notifications doesn't work properly on Android with UnifiedPush
+For additional Accounts no UnifiedPush is setup to receive Push Notification on Android
```

Or something that way?
We have here to much issues related with Push-Notification

**Comment by Mikaela** [comment]
If I understand correctly, #1299 describes the actual root cause of this issue, which isn't specific to UnifiedPush, so I am closing this one as a duplicate instead.

Thanks for bringing it to my attention @wrenix

**Comment by wrenix** [comment]
I believe we should keep the older (this issues) for more/better (debug) comments and because it has more participants which are listing if it got fixed in FluffyChat.

And change here the title and description on a way, that it could easier be find (and no new duplicated are created).

Warning: do not change the issue on a bigger scope to an "Notification does not work" and then to an "Fluffychat" does not work.

**Comment by kairusds** [comment]
Still the same issue today, April 10 2026

**Comment by wrenix** [comment]
FluffyChat and UnifiedPush is broken for years without reation of the developer. But there is a fork, which looks good: https://github.com/ExteraApp/Extera/issues/26 (just small things todo there with UnifiedPush, it is already usable)

https://extera.xyz/

**Comment by dam0n1sd** [comment]
Same problem at the moment - 18 Apr 2026. Notifications are sent only to the first account.
FluffyChat - 2.5.1
iOS - 16.1.1
Two accounts

**Account 1 - @user1:homeserver-one.tld (main and the first. Homeserver N1)**
Settings \ Notifications \ Devices - FluffyChat ios - chat.fluffy.fluffychathttps://[push.fluffychat.im/_matrix/push/v1/notify](http://push.fluffychat.im/_matrix/push/v1/notify)

**Account 2 - @user2:homeserver-two.tld (Homeserver N2)**
Settings \ Notifications \ Devices - No devices found

I really miss notifications for my second account. Without this feature, this app becomes useless.

**Comment by kairusds** [comment]
> Still the same issue today, April 10 2026

I've moved to using SchildiChat Next for now from F-droid and UnifiedPush works perfect there

**Comment by dam0n1sd** [comment]
> Now send the resulting json object to the second account's api, to set the pusher:
> 
> ```
> curl -XPOST -H "Content-Type: application/json" \
>   -H "Authorization: Bearer ${ACCESS_TOKEN_2}" \
>   --data '{"app_display_name":"..."... ,"append":true}' \
>   "${MATRIX_HOST_2}/_matrix/client/v3/pushers/set"
> ```

Perfect!
@squatica  - You're just a hacker.

Now notifications are sent to both the first and second accounts. True, clicking on the push notification opens the active account. But this is much better than before. 
Thank you! Your solution is elegant :)

**Comment by krille-chan** [comment]
Will be fixed soon by #2921 

> FluffyChat and UnifiedPush is broken for years without reation of the developer. But there is a fork, which looks good: [ExteraApp/Extera#26](https://github.com/ExteraApp/Extera/issues/26) (just small things todo there with UnifiedPush, it is already usable)
> 
> https://extera.xyz/

UnifiedPush is tested for every release with ntfy and works fine

**Comment by heini** [comment]
As far as I can see, #2921 made it into 2.6.0, but on 2.7.2 I still get no notifications from FluffyChat.

**Comment by wrenix** [comment]
@krille-chan only with one provider installed (just ntfy.sh, just try installing Sunup beside ntfy.sh) and only with one account in fluffychat, otherwise some of this bugs would be solved already.

**Comment by krille-chan** [comment]
hmm, looks like this is a little bit more complicated. I'll add a small troubleshoot section in the notification settings
