### ISSUE TITLE
Support for Linux systems which don't use NetworkManager or systemd

### ISSUE THREAD

**Issue by burningserenity** [krille-chan/fluffychat#572]
### Feature Description

Right now, it is not possible to join a room if NetworkManager is not running. Trying to do so results in this error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.NetworkManager was not provided by any .service files
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1102)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:64)
<asynchronous suspension>

flutter: dynamic_color: Accent color detected.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Provider<MatrixState> not found for PublicRoomBottomSheet
#0      Provider._inheritedElementOf (package:provider/src/provider.dart:343)
#1      Provider.of (package:provider/src/provider.dart:293)
#2      Matrix.of (package:fluffychat/widgets/matrix.dart:56)
#3      PublicRoomBottomSheet._joinRoom (package:fluffychat/widgets/public_room_bottom_sheet.dart:31)
#4      PublicRoomBottomSheet.build.<anonymous closure> (package:fluffychat/widgets/public_room_bottom_sheet.dart:98)
#5      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#18     _invoke1 (dart:ui/hooks.dart:186)
#19     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:119)
```

It is currently possible to join a room in a different client and then chat using Fluffychat.

### Rationale

Not every Linux user has NetworkManager and systemd installed, and I'm not sure why they're necessary.

**Comment by bellebaum** [comment]
I am running into the same problem. Can someone please reopen this?
