### ISSUE TITLE
Not able to join public rooms from fluffychat finder

### ISSUE THREAD

**Issue by scmanjarrez** [krille-chan/fluffychat#588]
### Bug Description

Clicking join room shows the following error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:441)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:705)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1018)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567)
#8      _invoke2 (dart:ui/hooks.dart:202)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:331)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:736)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:114)
```

### Steps to Reproduce

1. Find a room (i.e. #fluffychat:matrix.org)
2. Open it and click `Join room`
3. Nothing happens, but the terminal running fluffychat shows the above error

### Expected Behavior

Be able to join rooms

### App Version

1.14.1

### Additional Platform Information

flatpak

### Additional Context

![image](https://github.com/krille-chan/fluffychat/assets/9284124/a4e97281-ed2d-411a-9faf-9c03b57e7df6)

**Comment by Titaniumtown** [comment]
I can reproduce this on fedora silverblue with version 1.14.4
