### ISSUE TITLE
Ignoring users and Ignored users list are broken

### ISSUE THREAD

**Issue by LFd3v** [krille-chan/fluffychat#688]
### Bug Description

I am sure it worked in the past, but unfortunately I cannot say when the problem started, but the "Ignored users" list in Settings > Security is always empty in FluffyChat v1.15.0 and v1.15.1, both on desktop (Linux) and mobile (iOS and Android).

Also, trying to ignore users from their profile info silently fails, while it works if the MXID is added manually in "Ignored users", but the list remains empty.

I think all three are related, but please feel free to ask me to open separated issues for each of them if this helps somehow.

### Steps to Reproduce

Empty list:
1. Go to Settings > Security > Ignored list
2. List is empty, even if there are actually any ignored MXID in other clients

Cannot ignore user:
1. Click on an user profile picture to display their profile info
2. Click on Ignore (top right)
3. Nothing happens (user is not added to Ignored users, as it can be verified using other clients)

### Expected Behavior

Ignored users list should show all ignored MXIDs, and well as users should be able to add new ones clicking on Ignore in their profile info.

### App Version

1.15.0+

### Additional Platform Information

Linux, Android, iOS

### Additional Context

Linux, v1.15.1, error when clicking on Ignore in an user profile info:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      GoRouter.of (package:go_router/src/router.dart:503)
#1      GoRouterHelper.go (package:go_router/src/misc/extensions.dart:25)
#2      UserBottomSheetController.participantAction (package:fluffychat/pages/user_bottom_sheet/user_bottom_sheet.dart:242)
#3      UserBottomSheetView.build.<anonymous closure> (package:fluffychat/pages/user_bottom_sheet/user_bottom_sheet_view.dart:51)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:281)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
#13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#17     _invoke1 (dart:ui/hooks.dart:186)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:119)
```

Error when manually adding a MXID to the Ignored users:
```
flutter: [Matrix] Current sync request ID has changed. Dropping this sync loop!
```

In app log does not show any errors.

Using another client it is possible to verify that the MXID added manually was included in the Ignored users list, as well as it is possible to remove them.

**Comment by LFd3v** [comment]
As of v1.16.0, the Blocked Users list (I am not sure it changed its name or not, I think it was called Ignored Users when I opened this issue) is working, tested on iOS and Linux.

Blocking new users works now, but there is a minor problem with the UX:

1. When blocking an user from their profile, the MXID is filled in the Blocked Users page, and when it is accepted (tap on check-mark), it seems that nothing happens because the new MXID cannot be seen in the list, however a new sync is started and if the Blocked Users page is opened after the sync finishes then the new MXID can be seen.
2. Similarly, when removing a blocked user (tapping on the trash icon next to MXID) it seems that nothing happens, by as above if the Blocked Users page is opened after the re-sync, the MXID is not there anymore.

So I will not close the issue, but please feel free to do so if the above is not important, by design, or "won't fix".

Thanks again for FluffyChat!

**Comment by LFd3v** [comment]
It seems that there is a delay when the MXID is added or removed from the Blocked Users list while FluffyChat re-syncs, so it is not a big deal (i.e. if the user waits long enough then the list is updated accordingly).

Personally I think that some animation while the apps is re-syncing would be a better UX, but it is a minor issue. Of course, I can open a new issue for the RFE if requested.

Closing this issue. Thanks again for FluffyChat!
