### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by Th0mms3n** [krille-chan/fluffychat#755]
- Operating system: web
- Version: 1.16.1

### Exception
Provider<minified:H6> not found for minified:Um

### StackTrace
Provider<minified:H6> not found for minified:Um
    at Object.j (https://fluffychat.im/web/main.dart.js:5608:19)
    at Object.T (https://fluffychat.im/web/main.dart.js:5617:14)
    at Object.am (https://fluffychat.im/web/main.dart.js:51205:20)
    at bpA.$1 (https://fluffychat.im/web/main.dart.js:91186:197)
    at Um.aFi (https://fluffychat.im/web/main.dart.js:109905:22)
    at a5T.C (https://fluffychat.im/web/main.dart.js:109970:11)
    at lI.eP (https://fluffychat.im/web/main.dart.js:141584:28)
    at lI.zd (https://fluffychat.im/web/main.dart.js:141558:9)
    at lI.zd (https://fluffychat.im/web/main.dart.js:141594:11)
    at lI.aa_ (https://fluffychat.im/web/main.dart.js:141510:10)

**Comment by krille-chan** [comment]
Thanks, should be fixed now
