### ISSUE TITLE
[BUG]: Error while delete error events action

### ISSUE THREAD

**Issue by compuguy** [krille-chan/fluffychat#756]
- Operating system: web
- Version: 1.16.1

### Exception
Unsupported operation: removeWhere

### StackTrace
Unsupported operation: removeWhere
    at Object.j (https://fluffychat.im/web/main.dart.js:5608:19)
    at Object.T (https://fluffychat.im/web/main.dart.js:5617:14)
    at F.hW (https://fluffychat.im/web/main.dart.js:70099:31)
    at https://fluffychat.im/web/main.dart.js:223407:3
    at c8r.a (https://fluffychat.im/web/main.dart.js:7025:62)
    at c8r.$2 (https://fluffychat.im/web/main.dart.js:71904:14)
    at c6n.$1 (https://fluffychat.im/web/main.dart.js:71898:21)
    at aK5.a_h (https://fluffychat.im/web/main.dart.js:73234:34)
    at bV6.$0 (https://fluffychat.im/web/main.dart.js:72375:11)
    at Object.RK (https://fluffychat.im/web/main.dart.js:7183:40)

**Comment by compuguy** [comment]
This may be related to this: https://github.com/krille-chan/fluffychat/issues/735#issuecomment-1868953427

**Comment by krille-chan** [comment]
Thanks, should be fixed now. At least I can no longer reproduce it on fluffychat.im/nightly please reopen if it happens again

**Comment by compuguy** [comment]
Yes I looked at #735 and tried the web nightly. That seemed to resolve that issue! 🎉
