### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by popey** [krille-chan/fluffychat#766]
- Operating system: web
- Version: 1.17.0

### Exception
RangeError (index): Index out of range: index should be less than 10: 35

### StackTrace
RangeError (index): Index out of range: index should be less than 10: 35
    at Object.j (https://fluffychat.im/web/main.dart.js:5622:19)
    at F.h (https://fluffychat.im/web/main.dart.js:70506:39)
    at Object.t (https://fluffychat.im/web/main.dart.js:193:15)
    at aZV.$2 (https://fluffychat.im/web/main.dart.js:90484:20)
    at qe.aiW (https://fluffychat.im/web/main.dart.js:148318:14)
    at bHl.$1 (https://fluffychat.im/web/main.dart.js:152279:34)
    at Ak.ap (https://fluffychat.im/web/main.dart.js:75955:30)
    at Ql.zi (https://fluffychat.im/web/main.dart.js:152216:56)
    at Ql.eA (https://fluffychat.im/web/main.dart.js:152191:11)
    at a3I.qb (https://fluffychat.im/web/main.dart.js:141925:3)

**Comment by krille-chan** [comment]
Duplication of https://github.com/krille-chan/fluffychat/issues/770 and fixed :)
