### ISSUE TITLE
[BUG]: Unable to load timeline

### ISSUE THREAD

**Issue by farribeiro** [krille-chan/fluffychat#789]
- Operating system: android
- Version: 1.17.0

### Exception
Concurrent modification during iteration: Instance(length:31) of '_GrowableList'.

### StackTrace
#0      ListIterator.moveNext (dart:_internal/iterable.dart:348)
#1      Room.getTimeline (package:matrix/src/room.dart:1502)
<asynchronous suspension>
#2      ChatController._getTimeline (package:fluffychat/pages/chat/chat.dart:338)
<asynchronous suspension>
#3      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624)
<asynchronous suspension>

**Comment by farribeiro** [comment]
https://github.com/krille-chan/fluffychat/issues/799#issuecomment-1890859022
