### ISSUE TITLE
[BUG]: Unable to open SSSS with recovery key

### ISSUE THREAD

**Issue by amandasystems** [krille-chan/fluffychat#866]
- Operating system: ios
- Version: 1.17.2

### Exception
RangeError (length): Invalid value: Valid value range is empty: 0

### StackTrace
#0      SSSS.decodeRecoveryKey (package:matrix/encryption/ssss.dart)
#1      OpenSSSS.unlock (package:matrix/encryption/ssss.dart:715)
#2      OpenSSSS.unlock (package:matrix/encryption/ssss.dart:692)
#3      BootstrapDialogState.build.<anonymous closure> (package:fluffychat/pages/bootstrap/bootstrap_dialog.dart:293)
#4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)

**Comment by LFd3v** [comment]
1. Can you please check if it still happens with the latest version (v1.17.3 as of now)?

2. If it does, can you please provide the steps to reproduce it and explain what SSSS means?

Thank you

**Comment by amandasystems** [comment]
If I see the bug again I’ll let you know; I can’t remember precisely what I was doing, the output (including “SSSS”, which I also recall reacting to) came from a crash log. I don’t think I was doing anything particularly weird at the moment.

For now, you can just close it. I’ll be sure to write more if it appears again.
