### ISSUE TITLE
[BUG]: Unable to play video

### ISSUE THREAD

**Issue by RoootTheFox** [krille-chan/fluffychat#874]
- Operating system: android
- Version: 1.17.2

### Exception
FileSystemException: Cannot open file, path = '/data/user/0/chat.fluffy.fluffychat/cache/attachments%7C578763260682043412%7C1177665643655475312%7Cy2mate.is_-_One_to_Ten_shorts_fortnite_gaming_animation_animated_meme_fyp_art_kit_meowskulls_funny-I8sv1uY27Fw-720p-1700770049.mp4_y2mate.is_-_One_to_Ten_shorts_fortnite_gaming_animation_animated_meme_fyp_art_kit_meowskulls_funny-I8sv1uY27Fw-720p-1700770049.mp4' (OS Error: File name too long, errno = 36)

### StackTrace
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381)
<asynchronous suspension>
#2      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634)
<asynchronous suspension>
#3      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:47)
<asynchronous suspension>

**Comment by RoootTheFox** [comment]
just checked, this also happens on 1.17.3 (latest version)

**Comment by RoootTheFox** [comment]
yes, it is running on android.

Software/HW information:
- Phone: **Samsung Galaxy S23+**
- OS: **Android 14**, OneUI 6.0
- Kernel version: **5.15.94-android13-8-27763874-abS916BXXS3BWL3**

on another note: this could also be mitigated by hashing the URL, and using the hash as internal filename instead.
