### ISSUE TITLE
[BUG]: Error Widget

### ISSUE THREAD

**Issue by lil5** [krille-chan/fluffychat#880]
- Operating system: MacOS
- Version: 1.17.3

### Exception
```log
Null check operator used on a null value

### StackTrace
#0      Room.ownPowerLevel (package:matrix/src/room.dart:1808)
#1      Room.canSendEvent (package:matrix/src/room.dart:1964)
#2      Room.canSendDefaultMessages (package:matrix/src/room.dart:1918)
#3      ChatView.build.<anonymous closure>.<anonymous closure> (package:fluffychat/pages/chat/chat_view.dart:283)
#4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:609)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
```

**Comment by krille-chan** [comment]
macOS version is not officially supported. Please add steps to reproduce
