### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by mewtrino** [krille-chan/fluffychat#928]
- Operating system: ios
- Version: 1.18.0
- Phone: iPhone SE Gen 3

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.7fc37644-7d83-43cd-8499-dc87b0c2fae2)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by SvenXP** [comment]
Same problem with iPhone 15 pro

**Comment by PolynomialDivision** [comment]
Same issue on the iPhone 17pro.
