### ISSUE TITLE
Send on Enter not working on Ubuntu 22.04 LTS Flatpak

### ISSUE THREAD

**Issue by tGitzHub** [krille-chan/fluffychat#944]
### Bug Description

For a view versions now, send on enter does not work for me. Trying to turn it off and on doesnt change that.
enter button just makes hard line break instead

### Steps to Reproduce

Write text in a chat
press enter
move mouse over and actually click on send button

### Expected Behavior

sending on enter

### App Version

1.18.0

### Additional Platform Information

PC (Ubuntu 22.10 LTS, Flatpak)

### Additional Context

this is my first github issue, i hope that's how it's done...

**Comment by fadelkon** [comment]
Same for me!

I'm on Debian 12 with this version of fluffychat

````
> flatpak info im.fluffychat.Fluffychat

fluffychat.im - Chat with your friends

          ID: im.fluffychat.Fluffychat
         Ref: app/im.fluffychat.Fluffychat/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.18.0
     License: AGPL-3.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 90,9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: c256e9624c7a01f07ebad1ea30c0cf12cb5f0c154e62e9d0c179884789547290
      Parent: 5eaeed028f1e9e10ff4693a47a7636df6204ed7aeb0f431f616040725b049e51
     Subject: ci: Automerge flathub bot prs (4becf2cf)
        Date: 2024-02-25 14:26:15 +0000
````
and this version of flatpak, just in case:
```
> flatpak --version
Flatpak 1.14.4
```

**Comment by krille-chan** [comment]
I cannot reproduce this on Ubuntu 23.10 with FluffyChat installed as snap :-/

**Comment by kanru** [comment]
I can also reproduce, both with Wayland and X11.

Operating System: Fedora Linux 40.20240324.n.0 (Silverblue Prerelease)

[Screencast from 2024-03-25 08-00-39.webm](https://github.com/krille-chan/fluffychat/assets/17571/d6fe43a1-1edc-46e5-9417-26be934ddd35)

```
fluffychat.im - Chat with your friends

          ID: im.fluffychat.Fluffychat
         Ref: app/im.fluffychat.Fluffychat/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.18.0
     License: AGPL-3.0-only
      Origin: fedora-flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 90.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: c256e9624c7a01f07ebad1ea30c0cf12cb5f0c154e62e9d0c179884789547290
      Parent: 5eaeed028f1e9e10ff4693a47a7636df6204ed7aeb0f431f616040725b049e51
     Subject: ci: Automerge flathub bot prs (4becf2cf)
        Date: 2024-02-25 14:26:15 +0000

[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
devices=all;
filesystems=xdg-download;

[Session Bus Policy]
chat.fluffy.fluffychat=own
org.freedesktop.Notifications=talk
```

I notice that for each keypress there are severl lines of logs in console (not in the builtin log viewer)

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:451)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:875)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1164)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603)
#8      _invoke2 (dart:ui/hooks.dart:344)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257)
```

BTW, FluffyChat is fantastic.

**Comment by throwException** [comment]
I also see this issue on debian 12 with flatpak

> fluffychat.im - Chat with your friends
> 
>           ID: im.fluffychat.Fluffychat
>          Ref: app/im.fluffychat.Fluffychat/x86_64/stable
>         Arch: x86_64
>       Branch: stable
>      Version: 1.18.0
>      License: AGPL-3.0-only
>       Origin: flathub
>   Collection: org.flathub.Stable
> Installation: system
>    Installed: 90.9 MB
>      Runtime: org.freedesktop.Platform/x86_64/23.08
>          Sdk: org.freedesktop.Sdk/x86_64/23.08
> 
>       Commit: c256e9624c7a01f07ebad1ea30c0cf12cb5f0c154e62e9d0c179884789547290
>       Parent: 5eaeed028f1e9e10ff4693a47a7636df6204ed7aeb0f431f616040725b049e51
>      Subject: ci: Automerge flathub bot prs (4becf2cf)
>         Date: 2024-02-25 14:26:15 +0000
>

**Comment by kanru** [comment]
The dependency used for shortcuts is buggy

https://github.com/krille-chan/fluffychat/blob/f6c6898fb6f89f912ef57e6515c348a6c012c1c8/pubspec.yaml#L161-L165

It references `LogicalKeyboardKey.debugName -> String?`

https://github.com/TheOneWithTheBraid/keyboard_shortcuts/blob/a3d4020911860ff091d90638ab708604b71d2c5a/lib/keyboard_shortcuts.dart#L50-L52

The document says

> The debug string to print for this keyboard key, which will be null in release mode. 

https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html

**Comment by captn3m0** [comment]
https://github.com/AntoineMarcel/keyboard_shortcuts/pull/7/commits/6c542bd15cff2b22a9d0816fc693083cdae7e12e avoids using debugName, but it was reverted before the merge (?) https://github.com/AntoineMarcel/keyboard_shortcuts/pull/7

**Comment by spongythecake** [comment]
Compiled directly from source, v1.20.0, this exact same issue happens on my build.

**Comment by EvilOlaf** [comment]
Confirmed with flathub version 1.19.2 on Linux Mint (based on Ubuntu Jammy).

**Comment by kolorafa** [comment]
Same with flathub version 1.20.0 using Linux Arch

After opening app the console was floodded with the same message @kanru got:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:451)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:875)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1164)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:603)
#8      _invoke2 (dart:ui/hooks.dart:344)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45)
#10     _Channel.push (dart:ui/channel_buffers.dart:135)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:343)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:737)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:257)
```

**Comment by manuke42** [comment]
it seems the _Schortcuts_ widget is not working correctly here.
when i replace this line:
https://github.com/krille-chan/fluffychat/blob/cc828411243d9c1293027e008a0f90c68c4c905b/lib/pages/chat/input_bar.dart#L404

with:
`SingleActivator(LogicalKeyboardKey.enter): SubmitLineIntent(),`
then it works correctly for me on linux. But I can't say what else is breaking by that change (if at all).
The error message in the _keyboard_shortcuts_ package seems unrelated to this problem, that package seems to be only used for the emoji and file picker.

**Comment by tGitzHub** [comment]
issue seems to be gone with 1.21.2 on my computer (y)

**Comment by tGitzHub** [comment]
nope. no idea what ive done - i think i pasted something with ctrl-v - now it is back to not working :(

**Comment by NastyaGrifon** [comment]
Still not working for Flatpak

Versions: 
flatpak : `im.fluffychat.Fluffychat	1.22.1	stable`
uname -r : `6.10.11-1-MANJARO`

**Comment by tallthom** [comment]
I seem to have this issue on Ubuntu 24.04 as well.

![image](https://github.com/user-attachments/assets/aaadc93b-fe96-406e-af6a-e69487d21e30)

I cannot "send on enter" no matter what the setting in the "Settings-->Chat" is set to.

**Comment by Wohlstand** [comment]
I do have the same on Ubuntu 22.04 (Linux Mint, FlatPak), and on macOS too (AppStore version marked as for iPad).

**Comment by tofuwabohu** [comment]
Same issue on Endeavour OS, freshly installed 1.22.0 via [AUR](https://aur.archlinux.org/packages/fluffychat)

**Comment by hieronymousch** [comment]
Same here on Kubuntu with 1.21 snap

**Comment by Twig6943** [comment]
bump (pls fix I'm using nheko just because of this issue)

**Comment by baudtack** [comment]
Still experiencing this issue on Arch

**Comment by baudtack** [comment]
Also attempted to build from AUR and have the same issue.

**Comment by Duckbuster** [comment]
Toggling Numlock seems to fix this.
Arch Linux, using Flatpak FluffyChat.

**Comment by Twig6943** [comment]
> Toggling Numlock seems to fix this. Arch Linux, using Flatpak FluffyChat.

Just tested this on my machine and yea toggling Numlock does get it fixed

**Comment by tGitzHub** [comment]
> Toggling Numlock seems to fix this. Arch Linux, using Flatpak FluffyChat.

can confirm, also works for me! Good observation!

**Comment by Wohlstand** [comment]
> Toggling Numlock seems to fix this. Arch Linux, using Flatpak FluffyChat.

Tested on my end, it works too. However, it's still a bug, it should NOT depend on the state of Numpad. I use numpad often to type numbers, phones, etc. On macOS as I know is no numlock at all, and on macOS the same bug appears as well as on Linux. On macOS I use old Apple's keyboard that has different buttons.

**Comment by Duckbuster** [comment]
It's a very strange bug, and yeah I consider this a workaround, not a fix.

**Comment by noahbliss** [comment]
Not sure if this is related, but tab completion for tagging users also seems bugged. E.g. `@noa[TAB]` actually cancels the autocompletion pop up.

**Comment by jhebert8** [comment]
March 2025, issue is still present. Does this software still get updated?

**Comment by tokudan** [comment]
I'm seeing the same issue on NixOS with KDE Plasma.
Is there some information that we can still provide?
One potential solution was mentioned in https://github.com/krille-chan/fluffychat/issues/944#issuecomment-2161665529
What would be the next step? A pr?

**Comment by kanru** [comment]
I believe https://github.com/krille-chan/fluffychat/issues/944#issuecomment-2041454019 is the issue.

I think FluffyChat is not targeting Linux desktop; it seems mobile is the main focus. I just switched to Fractal.

As a workaround, you can try to run debug build.

**Comment by NastyaGrifon** [comment]
Still happens for version 1.25.0. Hope it gets fixed soon. 

Fractal is a valid option, but I still prefer FC if it worked as intended

**Comment by arscynic** [comment]
> Still happens for version 1.25.0. Hope it gets fixed soon.
> 
> Fractal is a valid option, but I still prefer FC if it worked as intended.
> 
> UPDATE: Toggling Num Lock fixed the "Send message on Enter". It now works regardless of the Num Lock state! Hooray?

What a peculiar ~~fix~~ workaround. Works for me as well on _EndeavourOS_.

**Comment by kolAflash** [comment]
Why does ctrl+enter not work here?

**Comment by jhebert8** [comment]
I will try this tomorrow

**Comment by Wohlstand** [comment]
Just now I tested, thing is no longer happens on my end, Ubuntu 24.04, the ENTER key works for ending perfectly. FluffyChat 2.6.0, FlatPak.
