### ISSUE TITLE
[BUG]: Unable to play video (or really even send it)

### ISSUE THREAD

**Issue by SokiAria** [krille-chan/fluffychat#960]
- Operating system: android
- Version: 1.17.1

### Exception
This event hasn't any attachment or thumbnail.

### StackTrace
#0      Event.downloadAndDecryptAttachment (package:matrix/src/event.dart:605)
#1      EventVideoPlayerState._downloadAction (package:fluffychat/pages/chat/events/video_player.dart:36)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:492)
#9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)

**Comment by krille-chan** [comment]
Closing as duplicate of #941
