### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by Happyfeet01** [krille-chan/fluffychat#966]
happens when I would play an voicemessage from the WhatsApp bridge 

- Operating system: ios
- Version: 1.19.0

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.dd1a643a-5741-4646-a971-322cda9b15f1)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by Happyfeet01** [comment]
Here is the logmessage.

`MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.44539555-d527-45f7-a5c0-ff0ebfebbdaf)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:982)
<asynchronous suspension>
`

**Comment by krille-chan** [comment]
Closing as duplicate of #928
