### ISSUE TITLE
fluffychat voids out when rotated twice

### ISSUE THREAD

**Issue by Gonzukum** [krille-chan/fluffychat#974]
### Bug Description

Log:
```
1712096662.291 10274 18444 18444 I uffy.fluffychat: Using CollectorTypeCMC GC.
1712096662.294 10274 18444 18444 E uffy.fluffychat: Not starting debugger since process cannot load the jdwp agent.
1712096662.309 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10274; state: ENABLED
1712096662.309 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10274; state: DISABLED
1712096662.317 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.arm64_v8a.dm': No such file or directory
1712096662.317 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.arm64_v8a.dm': No such file or directory
1712096662.318 10274 18444 18444 W uffy.fluffychat: Entry not found
1712096662.318 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.en.dm': No such file or directory
1712096662.318 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.en.dm': No such file or directory
1712096662.318 10274 18444 18444 W uffy.fluffychat: Entry not found
1712096662.318 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.es.dm': No such file or directory
1712096662.318 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.es.dm': No such file or directory
1712096662.318 10274 18444 18444 W uffy.fluffychat: Entry not found
1712096662.319 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.xxhdpi.dm': No such file or directory
1712096662.319 10274 18444 18444 W ziparchive: Unable to open '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.xxhdpi.dm': No such file or directory
1712096662.319 10274 18444 18444 W uffy.fluffychat: Entry not found
1712096662.320 10274 18444 18444 D nativeloader: Configuring clns-4 for other apk /data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/base.apk:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.arm64_v8a.apk:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.en.apk:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.es.apk:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.xxhdpi.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/lib/arm64:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/base.apk!/lib/arm64-v8a:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZc
1712096662.325 10274 18444 18444 V GraphicsEnvironment: Currently set values for:
1712096662.325 10274 18444 18444 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
1712096662.325 10274 18444 18444 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
1712096662.325 10274 18444 18444 V GraphicsEnvironment: Global.Settings values are invalid: number of packages: 0, number of values: 0
1712096662.325 10274 18444 18444 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
1712096662.328 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10274; state: ENABLED
1712096662.328 10274 18444 18444 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
1712096662.330 10274 18444 18444 I FirebaseInitProvider: FirebaseApp initialization successful
1712096662.333 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 279646685; UID 10274; state: DISABLED
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/lib/arm64'
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/base.apk!/lib/arm64-v8a'
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.arm64_v8a.apk!/lib/arm64-v8a'
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.en.apk!/lib/arm64-v8a'
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.es.apk!/lib/arm64-v8a'
1712096662.339 10274 18444 18467 D vulkan  : searching for layers in '/data/app/~~7Hp5uAK-Th0jfHBzo5J_JQ==/chat.fluffy.fluffychat-LVEQ0Q-YpYIFKNvLVQZcBw==/split_config.xxhdpi.apk!/lib/arm64-v8a'
1712096662.340 10274 18444 18467 I DMABUFHEAPS: Using DMA-BUF heap named: vframe-secure
1712096662.342 10274 18444 18444 I MultiDex: VM with version 2.1.0 has multidex support
1712096662.342 10274 18444 18444 I MultiDex: Installing application
1712096662.342 10274 18444 18444 I MultiDex: VM has multidex support, MultiDex support library is disabled.
1712096662.342 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 309578419; UID 10274; state: DISABLED
1712096662.390 10274 18444 18444 D FlutterFileDialogPlugin: onAttachedToEngine - IN
1712096662.390 10274 18444 18444 D FlutterFileDialogPlugin: doOnAttachedToEngine - IN
1712096662.390 10274 18444 18444 D FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
1712096662.390 10274 18444 18444 D FlutterFileDialogPlugin: onAttachedToEngine - OUT
1712096662.391 10274 18444 18444 D Plugin  : onAttachedToEngine
1712096662.392 10274 18444 18444 D FlutterFileDialogPlugin: onAttachedToActivity
1712096662.392 10274 18444 18444 D FlutterFileDialogPlugin: doOnAttachedToActivity - IN
1712096662.392 10274 18444 18444 D FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
1712096662.395 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 232195501; UID 10274; state: DISABLED
1712096662.412 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10274; state: DISABLED
1712096662.427 10274 18444 18444 D VRI[MainActivity]: Canceling draw. cancelDueToPreDrawListener=true cancelDueToSync=false
1712096662.429 10274 18444 18444 W FlutterWebRTCPlugin: audioFocusChangeListener [Earpiece(name=Earpiece)] Earpiece(name=Earpiece)
1712096662.429 10274 18444 18444 W FlutterWebRTCPlugin: audioFocusChangeListener [Speakerphone(name=Speakerphone), Earpiece(name=Earpiece)] Speakerphone(name=Speakerphone)
1712096662.434 10274 18444 18481 I flutter : [Matrix] [32mWelcome to FluffyChat <3[0m
1712096662.467 10274 18444 18481 I flutter : *** sqflite warning ***
1712096662.467 10274 18444 18481 I flutter : You are changing sqflite default factory.
1712096662.467 10274 18444 18481 I flutter : Be aware of the potential side effects. Any library using sqflite
1712096662.467 10274 18444 18481 I flutter : will have this factory as the default for all operations.
1712096662.467 10274 18444 18481 I flutter : *** sqflite warning ***
1712096662.903 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096662.903 10274 18444 18444 D Plugin  : Method: initialized
1712096662.931 10274 18444 18444 D Plugin  : Method: getDistributors
1712096662.932 10274 18444 18481 I flutter : dynamic_color: Core palette detected.
1712096662.932 10274 18444 18481 I flutter : initializeCallback finished
1712096662.972 10274 18444 18444 D VRI[MainActivity]: Draw frame after cancel
1712096667.478 10274 18444 18548 D ProfileInstaller: Installing profile for chat.fluffy.fluffychat
1712096673.286 10274 18444 18444 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10274; state: ENABLED
1712096673.517 10274 18444 18444 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
1712096673.517 10274 18444 18444 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
1712096673.518 10274 18444 18444 D Plugin  : Method: getDistributors
1712096673.519 10274 18444 18444 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
1712096673.519 10274 18444 18444 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
1712096673.521 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096673.601 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096675.160 10274 18444 18444 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
1712096675.160 10274 18444 18444 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
1712096675.161 10274 18444 18444 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
1712096675.161 10274 18444 18444 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
1712096675.161 10274 18444 18444 D Plugin  : Method: getDistributors
1712096675.165 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096675.201 10274 18444 18481 I flutter : Null check operator used on a null value
1712096675.201 10274 18444 18481 I flutter : #0      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3343)
1712096675.201 10274 18444 18481 I flutter : #1      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2619)
1712096675.201 10274 18444 18481 I flutter : #2      _HeroFlight.onTick (package:flutter/src/widgets/heroes.dart:633)
1712096675.201 10274 18444 18481 I flutter : #3      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161)
1712096675.201 10274 18444 18481 I flutter : #4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161)
1712096675.201 10274 18444 18481 I flutter : #5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:161)
1712096675.201 10274 18444 18481 I flutter : #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:865)
1712096675.201 10274 18444 18481 I flutter : #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:258)
1712096675.201 10274 18444 18481 I flutter : #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386)
1712096675.201 10274 18444 18481 I flutter : #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1233)
1712096675.201 10274 18444 18481 I flutter : #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
1712096675.201 10274 18444 18481 I flutter : #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1231)
1712096675.201 10274 18444 18481 I flutter : #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1148)
1712096675.201 10274 18444 18481 I flutter : #13     _invoke1 (dart:ui/hooks.dart:328)
1712096675.201 10274 18444 18481 I flutter : #14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:361)
1712096675.201 10274 18444 18481 I flutter : #15     _beginFrame (dart:ui/hooks.dart:272)
1712096675.218 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096675.223 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.257 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.279 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.301 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.323 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.346 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.357 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.368 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.379 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096675.390 10274 18444 18481 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
1712096676.283 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096677.490 10274 18444 18444 D VRI[MainActivity]: visibilityChanged oldVisibility=true newVisibility=false
1712096677.526 10274 18444 18444 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
1712096677.526 10274 18444 18444 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
1712096677.526 10274 18444 18444 D VRI[MainActivity]: Not drawing due to not visible
1712096677.530 10274 18444 18444 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
1712096677.536 10274 18444 18444 D VRI[MainActivity]: applyTransactionOnDraw applyImmediately
1712096677.720 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - false[0m
1712096677.720 10274 18444 18481 I flutter : [Matrix] [33mSet background mode in VOIP plugin - true[0m
```

### Steps to Reproduce

1. Rotate
2. Rotate back

https://github.com/krille-chan/fluffychat/assets/101081865/a8833e21-b33f-4a9e-b9c1-56a2958b9cf0

### Expected Behavior

When rotated and rotated back it doesn't void out

### App Version

1.19.0

### Additional Platform Information

rooted Google pixel 6 android 14 build number AP1A.240305.019.A1 stock rom

**Comment by Lexden12** [comment]
On Android (Pixel 7 Android 14) it seems to be voiding the screen regardless of what is focused (room list, a specific room, even settings). In the room list and a specific room, it is exclusively voided in portrait mode. Switching back to landscape will bring the view back (and then will void again if rotated to portrait again).
However, settings seems extra broken as this screen causes both landscape and portrait to void the screen after rotating in my experience.

**Comment by Haui1112** [comment]
> Note this really only seem to happen if you rotate while inside a chat room. If you are in the room list, this doesnt occur.

For completeness sake, the error doesnt occur but at least on my device (iphone 11 pro) the app becomes unusable anyway so although no error in roomlist, the problem still stands for me.

**Comment by Gonzukum** [comment]
It has been not fixed yet

**Comment by phtnnz** [comment]
Still an issue in 1.25.0

**Comment by krille-chan** [comment]
Closing as duplicate of #979 (iOS rotation crash / RenderFractionalTranslation)
